/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV1Projects200ItemStatus = typeof GetApiV1Projects200ItemStatus[keyof typeof GetApiV1Projects200ItemStatus];


export const GetApiV1Projects200ItemStatus = {
  draft: 'draft',
  published: 'published',
} as const;
