/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Index route
 */
export const GetApiV1Response = zod.object({
  "message": zod.string()
})

