/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiV1200
} from '../myAPI.schemas.fetch';

import { customFetch } from '../../mutators/custom-fetch';

export type getApiV1Response200 = {
  data: GetApiV1200
  status: 200
}

export type getApiV1ResponseSuccess = (getApiV1Response200) & {
  headers: Headers;
};
;

export type getApiV1Response = (getApiV1ResponseSuccess)

export const getGetApiV1Url = () => {




  return `/api/v1/`
}

/**
 * Index route
 */
export const getApiV1 = async ( options?: RequestInit): Promise<getApiV1Response> => {

  return customFetch<getApiV1Response>(getGetApiV1Url(),
  {
    ...options,
    method: 'GET'


  }
);}


