/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
export type GetApiV1200 = {
  message: string;
};

export type GetApiV1Projects200ItemStatus = typeof GetApiV1Projects200ItemStatus[keyof typeof GetApiV1Projects200ItemStatus];


export const GetApiV1Projects200ItemStatus = {
  draft: 'draft',
  published: 'published',
} as const;

export type GetApiV1Projects200Item = {
  id: string;
  slug: string;
  title: string;
  /** @nullable */
  description: string | null;
  content: string;
  status: GetApiV1Projects200ItemStatus;
  /** @nullable */
  coverImage: string | null;
  /** @nullable */
  liveUrl: string | null;
  /** @nullable */
  repoUrl: string | null;
  createdAt: string;
  /** @nullable */
  publishedAt: string | null;
  updatedAt: string;
};

