/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import type {
  GetApiV1Projects200Item
} from '../myAPI.schemas.fetch';

import { customFetch } from '../../mutators/custom-fetch';

export type getApiV1ProjectsResponse200 = {
  data: GetApiV1Projects200Item[]
  status: 200
}

export type getApiV1ProjectsResponseSuccess = (getApiV1ProjectsResponse200) & {
  headers: Headers;
};
;

export type getApiV1ProjectsResponse = (getApiV1ProjectsResponseSuccess)

export const getGetApiV1ProjectsUrl = () => {




  return `/api/v1/projects`
}

export const getApiV1Projects = async ( options?: RequestInit): Promise<getApiV1ProjectsResponse> => {

  return customFetch<getApiV1ProjectsResponse>(getGetApiV1ProjectsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}


