/**
 * Generated by orval v8.19.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const GetApiV1ProjectsResponseItem = zod.object({
  "id": zod.string(),
  "slug": zod.string(),
  "title": zod.string(),
  "description": zod.string().nullable(),
  "content": zod.string(),
  "status": zod.enum(['draft', 'published']),
  "coverImage": zod.string().nullable(),
  "liveUrl": zod.string().nullable(),
  "repoUrl": zod.string().nullable(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "publishedAt": zod.iso.datetime({"offset":true}).nullable(),
  "updatedAt": zod.iso.datetime({"offset":true})
})
export const GetApiV1ProjectsResponse = zod.array(GetApiV1ProjectsResponseItem)

