name: CI

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_TELEMETRY_DISABLED: 1

permissions:
  contents: read
  id-token: write

jobs:
  format:
    name: Format check
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          turbo-team: ${{ vars.TURBO_TEAM }}

      - run: bun run format:check

  lint:
    name: Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          turbo-team: ${{ vars.TURBO_TEAM }}

      - run: bun run lint

  typecheck:
    name: Typecheck
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          turbo-team: ${{ vars.TURBO_TEAM }}

      - run: bun run typecheck

  test:
    name: Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          turbo-team: ${{ vars.TURBO_TEAM }}

      - name: Create .dev.vars for tests
        working-directory: apps/api
        run: |
          cat <<EOF > .dev.vars
          ALLOWED_ORIGINS=http://localhost:3000
          BETTER_AUTH_URL=http://localhost:8787
          BETTER_AUTH_SECRET=${{ secrets.BETTER_AUTH_SECRET }}
          EOF

      - run: bun run test:coverage

      - name: "API Report Coverage"
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: apps/api

  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          turbo-team: ${{ vars.TURBO_TEAM }}

      - run: bun run build
